import dotenv from "dotenv";

dotenv.config();

const {
  DISCORD_TOKEN,
  GITHUB_APP_ID,
  GITHUB_APP_PRIVATE_KEY,
  GITHUB_APP_INSTALLATION_ID,
  GITHUB_OWNER,
  GITHUB_REPOSITORY,
  GITHUB_WEBHOOK_SECRET,
  DISCORD_CHANNEL_ID,
  DISCORD_GUILD_ID,
} = process.env;

if (
  !DISCORD_TOKEN ||
  !GITHUB_APP_ID ||
  !GITHUB_APP_PRIVATE_KEY ||
  !GITHUB_APP_INSTALLATION_ID ||
  !GITHUB_OWNER ||
  !GITHUB_REPOSITORY ||
  !GITHUB_WEBHOOK_SECRET ||
  !DISCORD_CHANNEL_ID ||
  !DISCORD_GUILD_ID
) {
  throw new Error("Missing environment variables");
}

export const config = {
  DISCORD_TOKEN,
  GITHUB_APP_ID: Number(GITHUB_APP_ID),
  GITHUB_APP_PRIVATE_KEY: Buffer.from(
    GITHUB_APP_PRIVATE_KEY,
    "base64",
  ).toString("utf8"),
  GITHUB_APP_INSTALLATION_ID: Number(GITHUB_APP_INSTALLATION_ID),
  GITHUB_OWNER,
  GITHUB_REPOSITORY,
  GITHUB_WEBHOOK_SECRET,
  DISCORD_CHANNEL_ID,
  DISCORD_GUILD_ID,
};
